; @file platformio.ini
; @brief PlatformIO build configuration for desktop unit testing and Adafruit Feather M0.
;
; @author Alberto Soncini <alberto.soncini3@studio.unibo.it>
; @author Supervisor: Carlo Caini <carlo.caini@unibo.it>
; @copyright Copyright (c) 2026 Alma Mater Studiorum, University of Bologna.

; PlatformIO Configuration File for muON-DTN
; Application stack operating atop the GGG framework

[platformio]
default_envs = adafruit_feather_m0

[env]
build_flags = 
    -I include
    -std=c++14
    -Wall
    -Wextra
lib_ldf_mode = deep+
extra_scripts = 
    pre:../ggg/scripts/apply_kconfig.py
lib_deps = 
    ../ggg

[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
lib_deps = 
    ${env.lib_deps}
    briscoetech/FreeRTOS_SAMD21 @ ^2.3.0
    jgromes/RadioLib @ ^7.6.0
    SPI
build_flags = 
    ${env.build_flags}
    -D TARGET_SAMD21

[env:native]
platform = native
test_framework = unity
build_flags = 
    ${env.build_flags}
    -D GGG_TARGET_NATIVE
    -D TARGET_NATIVE
    -D RUN_NATIVE_TESTS
lib_ignore = 
    RadioLib
lib_deps = 
    ${env.lib_deps}

